# Generated by Django 3.2.4 on 2023-09-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_batch_college_newbatches_placement_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=30, null=True)),
                ('profile', models.ImageField(null=True, upload_to='static/profile/')),
                ('course', models.CharField(max_length=30, null=True)),
                ('pyear', models.CharField(max_length=30, null=True)),
                ('college', models.CharField(max_length=200, null=True)),
                ('batch', models.CharField(max_length=40, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
