# Generated by Django 3.2.4 on 2023-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_registration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='passwd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
