# Generated by Django 3.2.4 on 2023-09-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_registration_passwd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='session',
            new_name='session_year',
        ),
    ]
