# Generated by Django 3.2.4 on 2023-09-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_session_session_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='batchid',
            field=models.IntegerField(null=True),
        ),
    ]
