# Generated by Django 3.2.4 on 2024-04-24 05:49

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapy', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
