# Generated by Django 3.2.4 on 2023-09-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200, null=True)),
                ('college_picture', models.ImageField(null=True, upload_to='static/college/')),
            ],
        ),
        migrations.CreateModel(
            name='newbatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch_pic', models.ImageField(null=True, upload_to='static/newbatches/')),
                ('starting_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_picture', models.ImageField(null=True, upload_to='static/placement/')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='static/company')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.batch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.college')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.session')),
            ],
        ),
    ]
