# Generated by Django 3.2.4 on 2023-09-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(default='registration', max_length=200, primary_key=True, serialize=False),
        ),
    ]
