# Generated by Django 3.2.4 on 2023-09-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230915_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
